version: '3.8'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.14.0
    volumes:
      - app_data:/app/data
    networks:
      - traefik_public
      - monitoring
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.uptime-kuma.rule: "Host(`uptime.${DOMAIN:?}`)"
        traefik.http.routers.uptime-kuma.entrypoints: "websecure"
        traefik.http.routers.uptime-kuma.tls.certresolver: "letsencrypt"
        traefik.http.services.uptime-kuma.loadbalancer.server.port: 3001
        traefik.http.routers.uptime-kuma.service: "uptime-kuma"
        traefik.http.routers.uptime-kuma.middlewares: uptime-kuma-auth@docker
        traefik.http.middlewares.uptime-kuma-auth.forwardauth.address: http://cloudflare-auth:8080/auth/${CLOUDFLARE_AUTH_AUD:?}
        prometheus-job: uptime-kuma
volumes:
  app_data:
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER:?},nfsvers=4
      device: :/uptime-kuma_app_data

networks:
  traefik_public:
    external: true
  monitoring:
    external: true
